services:
  nginx:
    image: duongbd1997/demo-nginx:${NGINX_VERSION}
    container_name: demo-nginx
    ports:
      - "8080:80"
    # env_file:
    #   - /opt/myapp/.env   # ðŸ‘ˆ file secret trÃªn VPS (khÃ´ng commit)
    restart: always